name: Build and Release

on:
  push:
    # Triggers on commits that match the release pattern
    branches: [ "main" ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Extract version and description
        id: release_info
        run: |
          if [[ "${{ github.event.head_commit.message }}" =~ release\((.*?)\):(.*) ]]; then
            echo "version=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
            echo "description=${BASH_REMATCH[2]}" >> $GITHUB_OUTPUT
            echo "is_release=true" >> $GITHUB_OUTPUT
          else
            echo "is_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Build with Gradle
        run: ./gradlew clean shadowJar

      - name: Create Release
        if: steps.release_info.outputs.is_release == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.release_info.outputs.version }}
          name: Release v${{ steps.release_info.outputs.version }}
          body: ${{ steps.release_info.outputs.description }}
          files: build/libs/PwnedCraft.jar
          draft: false
          prerelease: false